name: Trivy Image Scan

on: [push]
       
jobs:  
  build:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnerables/web-dvwa:latest'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: "Upload results to DefectDojo"
        if: ${{ always() }}
        run: |
          curl -X POST -H 'Authorization: Token d6090b0a240a471c888d38ba80dc5f4de46d277a' -H 'content-type: application/json' https://dojo-poc.prosegur.dev/api/v2/api-token-auth/ -d @trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
          
